apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-app
        image: nidhikyn12/deploy-nginx:4
        command: ['sh', '-c', 'echo hey there && sleep 3600']
        ports:
        - containerPort: 80
